// src/content.config.ts — Starlight's required content-collection
// definition. The `docs` collection is populated by
// src/content/docs/**, which is entirely generated by
// scripts/sync-docs.mjs (git-ignored; never hand-authored).
import { defineCollection } from "astro:content";
import { docsLoader } from "@astrojs/starlight/loaders";
import { docsSchema } from "@astrojs/starlight/schema";

export const collections = {
  docs: defineCollection({ loader: docsLoader(), schema: docsSchema() }),
};
